# Generated by Django 6.0.3 on 2026-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_signuprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
