# Generated by Django 6.0.3 on 2026-04-28 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Document', 'Document'), ('Guide', 'Guide'), ('Link', 'Link'), ('Handbook', 'Handbook'), ('Other', 'Other')], max_length=50)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('Word', 'Word'), ('Excel', 'Excel'), ('Link', 'Link'), ('Image', 'Image')], max_length=20)),
                ('file_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
