# Generated by Django 6.0.3 on 2026-03-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('account_created', models.BooleanField(default=False)),
            ],
        ),
    ]
