# Generated by Django 6.0.3 on 2026-04-01 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['graduation_year', 'first_name'], 'verbose_name_plural': 'People'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='account_created',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='area_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='best_communication_channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='course_offered',
            field=models.TextField(blank=True, null=True, verbose_name='Course offered at University'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='district_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('NOT SURE', 'Not Sure'), ('DECEASED', 'Deceased')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='field_of_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='home_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='index_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tell 2 (Airtel/UTL)'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='position_at_workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sector_of_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sir_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='title_roles',
            field=models.TextField(blank=True, null=True, verbose_name='Title/Roles'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='village_residence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Village/ward of residence'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tell 1 (MTN)'),
        ),
    ]
