# Generated by Django 6.0.3 on 2026-04-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_person_options_remove_person_account_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AYLFAlumni',
            fields=[
            ],
            options={
                'verbose_name': 'AYLF Alumni',
                'verbose_name_plural': 'AYLF Alumni',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('alumni.person',),
        ),
        migrations.CreateModel(
            name='COSAAlumni',
            fields=[
            ],
            options={
                'verbose_name': 'COSA Alumni',
                'verbose_name_plural': 'COSA Alumni',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('alumni.person',),
        ),
        migrations.CreateModel(
            name='YouthCorpsAlumni',
            fields=[
            ],
            options={
                'verbose_name': 'Youth Corps Alumni',
                'verbose_name_plural': 'Youth Corps Alumni',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('alumni.person',),
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-graduation_year', 'full_name'], 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='person',
            name='data_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='course_offered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_roles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='village_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
