# Generated by Django 6.0.3 on 2026-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alumniaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
