# Generated by Django 6.0.3 on 2026-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
